project:
  type: website
  output-dir: docs
website:  
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Mangroves Example"
        contents:
          - mangroves_preprocess.qmd
          - mangroves_plot.qmd