project:
  type: website
  output-dir: docs
website:
  title: example notebooks
  sidebar:
    contents: auto
    search: true
  repo-url: https://github.com/cboettig/example-notebooks
  repo-actions: [edit, issue]
  
  
#      - section: "Mangroves Example"
#        contents:
#          - mangroves_preprocess.qmd
#          - mangroves_plot.qmd