project:
  type: website
  output-dir: docs
website:
  title: example notebooks
  sidebar:
    contents: auto
    search: true

#      - section: "Mangroves Example"
#        contents:
#          - mangroves_preprocess.qmd
#          - mangroves_plot.qmd