



```{r include=FALSE}
knitr::opts_chunk$set(message=FALSE, warning = FALSE, eval = FALSE)
```


```{r}
library(sf)
library(stars)
library(glue)
library(tmap)
library(dplyr)
tmap_options(check.and.fix = TRUE)
tmap_mode("view")

```

```{r}
Sys.setenv("AWS_ACCESS_KEY_ID"="")
Sys.setenv("AWS_SECRET_ACCESS_KEY"="")
Sys.setenv("AWS_S3_ENDPOINT"="minio.carlboettiger.info")
Sys.setenv("AWS_VIRTUAL_HOSTING"="FALSE")

vsi <- "/vsis3"
bucket <- "biodiversity"
path <- "carbon/Vulnerable_Carbon_2018/Vulnerable_C_Total_2018.tif"

url <- glue::glue("{vsi}/{bucket}/{path}")
stars::read_stars(url)

```




```{r}
box <- spData::us_states |> dplyr::filter(NAME=="California")
box <- st_bbox(c(xmin=-124.5, ymin=40.5, xmax = -122, ymax=42), crs = 4326)


vsi <- "/vsicurl"
base <- "https://minio.carlboettiger.info"
bucket <- "biodiversity"
protected_areas_path <- "World-Protected-Areas-May2023.gdb"
carbon_total_2018_path <- "carbon/Vulnerable_Carbon_2018/Vulnerable_C_Total_2018.tif"


protected_areas <- glue("{vsi}/{base}/{bucket}/{protected_areas_path}")
carbon_total_2018 <- glue("{vsi}/{base}/{bucket}/{carbon_total_2018_path}")


```


```{r}
r <- stars::read_stars(carbon_total_2018) 
# box <- sf::st_transform(box, st_crs(r))
vulnerable_C_2018 <- r |> st_crop(box)
#tm_shape(vulnerable_C_2018) + tm_raster(palette = "Greens", alpha=0.5) + tm_graticules()

```


```{r}

sf_use_s2(FALSE) # Original data has misspecified spherical geometry actually...
loc <- spData::world |> dplyr::filter(name_long == "Spain")
## less RAM but WAY slower
wkt = st_as_text(st_geometry(loc))
PAs <- sf::read_sf(protected_areas,  wkt_filter = wkt) |> st_crop(box)
```


```{r}
tm_shape(vulnerable_C_2018) + tm_raster(palette = "Greens", alpha=0.5) +
  tm_shape(PAs) + tm_polygons("MANG_AUTH", alpha=0.8)

```


```{r}
library(sf)
library(bench)
mangroves_2015 = "/vsicurl/https://minio.carlboettiger.info/biodiversity/mangroves/GMW2015.parquet"
mangroves_2015 = "/vsicurl/https://minio.carlboettiger.info/biodiversity/mangroves/GMW2015.fgb"

mangroves_2015 = "/vsicurl/https://minio.carlboettiger.info/biodiversity/mangroves/GMW2015.gdb"

mangroves_2015 = "/vsizip/vsicurl/https://minio.carlboettiger.info/biodiversity/mangroves/GMW_v3_2015.zip"
loc <- spData::world |> dplyr::filter(name_long == "India")
## less RAM but WAY slower
wkt = st_as_text(st_geometry(loc)) # must crop at read-time

bench::bench_time({ # 17.6 minutes for S3
  m2015 <- st_read(mangroves_2015, wkt_filter = wkt)
})
plot(m2015)



bench::bench_time({ #
  m2015 <- st_read("GMW2015.gdb", wkt_filter = wkt)
})
plot(m2015)



```

